### ISSUE TITLE
Allow built-in storage streaming server to serve over HTTP scheme 

### ISSUE THREAD

**Issue by victorskl** [umccr/htsget-rs#101] opened 2022-06-21 02:33 UTC
Context:

- To allow Storage streaming server tower/Axum server to have option to configure either HTTP or HTTPS

Use Case:

- HTTP is still desirable for local dev because XHR JavaScript client (like the one embedded in  `igv.js`) will fail and block with local self-singed (local-trusted-ca) certs in browser

Prefer:

- Would be great; if it comes _out-of-the-box_ with HTTP scheme. Then, configurable to HTTPS as required.

**Comment by brainstorm** [comment] 2022-06-21 05:14
Duplicate of https://github.com/umccr/htsget-rs/issues/93?

**Comment by victorskl** [comment] 2022-06-21 05:16
(Ah) I thought it was discussed somewhere. Happy to close due to duplicate, yes.

**Closed** 2022-06-21 05:17 UTC
